package router

import (
	"ant-forum/handler/sd"
	"ant-forum/handler/v1/tags"
	"ant-forum/handler/v1/user"
	"ant-forum/router/middleware"

	_ "ant-forum/docs" // docs is generated by Swag CLI, you have to import it.

	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// Load loads the middlewares, routes, handlers.
func Load(g *gin.Engine, mw ...gin.HandlerFunc) *gin.Engine {
	// Middlewares.
	g.Use(gin.Recovery())
	g.Use(middleware.NoCache)
	g.Use(middleware.Options)
	g.Use(middleware.Secure)
	g.Use(mw...)
	// 404 Handler.
	g.NoRoute(func(c *gin.Context) {
		c.String(http.StatusNotFound, "The incorrect API route.")
	})
	// swagger api docs
	g.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	// api for authentication functionalities
	g.POST("/v1/login", user.Login)

	// The user handlers, requiring authentication
	u := g.Group("/v1/user")
	//u.Use(middleware.AuthMiddleware())
	{
		u.POST("", user.Create)
		u.DELETE("/:id", user.Delete)
		u.PUT("/:id", user.Update)
		u.GET("", user.List)
		u.GET("/:id", user.GetUserById)
	}
	t := g.Group("/v1/tags")
	{
		t.POST("", tags.Create)
		t.GET("", tags.List)
		t.DELETE("/:id", tags.Delete)
		t.GET("/:id", tags.GetTagById)
	}
	// The health check handlers
	svcd := g.Group("/sd")
	{
		svcd.GET("/health", sd.HealthCheck)
		svcd.GET("/disk", sd.DiskCheck)
		svcd.GET("/cpu", sd.CPUCheck)
		svcd.GET("/ram", sd.RAMCheck)
	}

	return g
}
